spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdata?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Sariel1998!


mybatis:
  configuration:
    map-underscore-to-camel-case: true #    开启驼峰命名映射
  mapper-locations: classpath:mapper/*.xml  # 加载 resource/mapper下的所有xml文件
  type-aliases-package: com.lagou.pojo # 配置xml映射文件中制定的实体类别名的扫描路径


